package com.ankush.EDI.Domain.Response;

import com.ankush.ReflectionUtils.Annotations.AutoGenerated;
import com.ankush.ReflectionUtils.Annotations.Insert;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
public class Response {
    @AutoGenerated
    public int id;
    @Insert
    public String username;
    @Insert
    public String question;
    @Insert
    public String answer;
}
