package com.ankush.EDI.Test;

import com.ankush.EDI.ReflectionUtils.Annotations.AutoGenerated;
import com.ankush.EDI.ReflectionUtils.Annotations.Insert;
import lombok.NoArgsConstructor;
import lombok.ToString;

@NoArgsConstructor
@ToString
public class TestDAO {
    @AutoGenerated
    public int id;
    @Insert(col = "name")
    public String name;


    public TestDAO(String name) {
        this.name = name;
    }
}
