package com.ankush.EDI.Domain.Surveys;

import com.ankush.ReflectionUtils.Annotations.AutoGenerated;
import com.ankush.ReflectionUtils.Annotations.Insert;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SurveyAnswer {
    @AutoGenerated
    int id;
    @Insert
    int surveyId;
    @Insert
    int number;
    @Insert
    String question;
    @Insert
    String answer;
}
